### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by fionnachan**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Compressed avatars and platform images

### CODE REVIEW

**Comment by nandiheath** [comment]
this will resize the photo to 200x200?
is it possible to maintain the original photo size?

**Comment by fionnachan** [comment]
avatars 200x200, platform long side 600px
I used this website: https://bulkresizephotos.com/
happy to stash my commits if any of you would like to compress the images to another size

**Comment by cswbrian** [comment]
@nandiheath I am OK with the compression. How about we ask @chunlaw to place the original images at dc-data?

**Comment by nandiheath** [comment]
my only concern is the SSR preview rendering
it is using 700x700 right now
need to test the actual outcome
but definitely yes if we could upload to dc-data

**Comment by cswbrian** [comment]
@fionnachan 
Can we create a directory for 100x100px optimized avatars that serve for the website instead?
https://trello.com/c/7w6NddNn/262-resize-all-avatar-to-100px-x-100px

**Pull request closed without merging**
